# Generated by Django 5.2 on 2025-04-18 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='images/')),
                ('president', models.CharField(blank=True, max_length=255)),
                ('coach', models.CharField(max_length=255)),
                ('found_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPP.country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPP.club')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPP.country')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_tft', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateField()),
                ('new_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_club', to='mainAPP.club')),
                ('old_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_club', to='mainAPP.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPP.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPP.season')),
            ],
        ),
    ]
