# Generated by Django 5.2 on 2025-04-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='date',
            field=models.DateField(auto_now_add=True, default='2025-04-21'),
            preserve_default=False,
        ),
    ]
